language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: azure_web_apps
  site:  prueba-azure.azurewebsites.net
  on: azure
  skip_cleanup: true
  username: prueba-azure\$prueba-azure
  password: kwvB5jLHapuWmXH7vBoMKRvAytCzuKzAJs7K8Lh2x9gt9buDWSbtPs6cpZsP
