language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: azure_web_apps
  site:  sesion6-github.azurewebsites.net
  on: master
  skip_cleanup: true
  username: sesion6-github\$sesion6-github
  password: xK5dBJMLn6gbM1GAsYZe0dolXPuCMP7FcimrZ6fsnQenc9p1syfiJbuNrjlZ
